select
    event_id,
    schema_version,
    event_type,
    event_time as event_ts,
    cast(event_time as date) as event_date,
    ingest_time as ingest_ts,
    user_id,
    session_id,
    device_os,
    device_os_version,
    device_app_version,
    geo_country,
    geo_region,
    geo_city,
    source_referrer,
    source_utm_campaign,
    source_utm_medium,
    product_id,
    category_id,
    brand,
    price,
    quantity,
    order_id,
    total_amount,
    payment_method,
    coupon_id,
    search_query,
    results_count,
    refund_amount,
    reason_code,
    payload_json,
    dt
from {{ source('lakehouse', 'silver_events') }}